
const router = require('express').Router()
const adminController = require('../controllers/adminController')
router.get('/login', adminController.login)
router.post('/signin', adminController.signin)
router.get('/logout', adminController.logout)
router.get('/dashboard', adminController.view)
router.get('/dashboard/:id', adminController.printpdf)
router.put('/dashboard/status', adminController.status)
router.put('/dashboard/gejala', adminController.gejala)
router.get('/register_manual', adminController.viewRegsiter_Manual)
router.get('/register_rfid', adminController.viewRegsiter_Rfid)
router.post('/register_rfid', adminController.addrfidoto)
router.get('/rfid', adminController.viewRfid)
router.post('/register_manual',adminController.addManual)
router.post('/rfid', adminController.addrfid)
router.put('/rfid', adminController.editrfid)
router.delete('/rfid/:id', adminController.deleterfid)
router.get('/users', adminController.viewUsers)
router.post('/users', adminController.registerUsers)
router.put('/users', adminController.editusers)
router.delete('/users/:id', adminController.deleteusers)
module.exports = router